### ISSUE TITLE
ServiceBusAdministrationClient support

### ISSUE THREAD

**Issue by deadwards90** [Azure/azure-service-bus-emulator-installer#17]
Our applications create their own queues / subscriptions on startup so that we don't have to manage that infrastructure elsewhere. We do this by interacting with Service Bus via `ServiceBusAdministrationClient`.

When trying to use that client via in combination with the emulator you will see the following error:

```
Unhandled exception. System.AggregateException: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (No connection could be made because the target machine actively refused it. (127.0.0.1:443)) (No connection could be made because the target machine actively refused it. (127.0.0.1:443)) (No connection could be made because the target machine actively refused it. (127.0.0.1:443)) (No connection could be made because the target machine actively refused it. (127.0.0.1:443))
 ---> Azure.RequestFailedException: No connection could be made because the target machine actively refused it. (127.0.0.1:443)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:443)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)        
   at Azure.Core.Pipeline.HttpClientTransport.ProcessSyncOrAsync(HttpMessage message, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessSyncOrAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.SendHttpRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.GetEntityAsync(String entityPath, String query, Boolean enrich, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.GetEntitiesPageAsync[T](String path, String nextSkip, Func`2 parseFunction, CancellationToken cancellationToken)
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Program.PublishMessageToDefaultQueue() in C:\Users\user\dev\temp\ServiceBusTest\ServiceBus.Emulator.Console.Sample\Program.cs:line 37
   at Program.PublishMessageToDefaultQueue() in C:\Users\user\dev\temp\ServiceBusTest\ServiceBus.Emulator.Console.Sample\Program.cs:line 37
   at Program.Main(String[] args) in C:\Users\user\dev\temp\ServiceBusTest\ServiceBus.Emulator.Console.Sample\Program.cs:line 15
   at Program.<Main>(String[] args)
```

I created this error by modifying the example with the following lines just after `Main` starts

```
var managementClient = new ServiceBusAdministrationClient(_connectionString);
await foreach(var page in managementClient.GetQueuesAsync())
{
    Console.WriteLine("Found page");
}
```

I'm guessing as of right now this client is just not supported. It's not mentioned anywhere in the documentation, at least that I could see.

This would be really useful to have.

**Comment by deadwards90** [comment]
Thanks @gkinsman, I missed that. I'll update the issue just to track support in that case.

**Comment by krishankumar95** [comment]
@Jeroen-Sturm ; Though AdminClient is not supported in this release; Duplicate detection is supported.

`RequiresDuplicateDetection` and `DuplicateDetectionHistoryTimeWindow` can be set within queue/subscription configuration in [config](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/ServiceBus-Emulator/Config/Config.json). 

For more details on config parameters refer : [Config Schema](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/ServiceBus-Emulator/Schema/Config-schema.json)

**Comment by Jeroen-Sturm** [comment]
> [@Jeroen-Sturm](https://github.com/Jeroen-Sturm) ; Though AdminClient is not supported in this release; Duplicate detection is supported.
> 
> `RequiresDuplicateDetection` and `DuplicateDetectionHistoryTimeWindow` can be set within queue/subscription configuration in [config](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/ServiceBus-Emulator/Config/Config.json).
> 
> For more details on config parameters refer : [Config Schema](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/ServiceBus-Emulator/Schema/Config-schema.json)

@krishankumar95 Thanks a lot, didn't look far enough..
That works as intended 👌🏻

**Comment by joshendriks** [comment]
+1

**Comment by mortenn** [comment]
MassTransit is another notable dependent of this feature, I hope Microsoft can priotitize adding this feature to the emulator, it seems to be quite limiting for adoption.

**Comment by KevinBDONL** [comment]
+1

**Comment by ArchitectureSellerpoint** [comment]
+1!
The emulator is frankly not useful, if ServiceBusAdministrationClient isn't supported.
Especially since the use of something like Masstransit is becoming part of common practice.
And Masstransit specifically, does not provide for a manual creation to work around it.

**Comment by 0xced** [comment]
\<snark\>
Let's keep upvoting this issue to get Microsoft's attention. It worked very well for the SQL Server Docker container with https://github.com/microsoft/mssql-docker/issues/2 (149 👍, opened in 2016) and https://github.com/microsoft/mssql-docker/issues/802 (183 👍, opened in 2023) 😂
\</snark\>

**Comment by SeanFeldman** [comment]
@0xced, the formula is a bit more sophisticated, involving upvotes and the age of the issue.

**Comment by Antwane** [comment]
+1

**Comment by blogdoft** [comment]
I would like to write a interface for emulator. So, users will be able to see the messages sent, drop them and etc. But, without admin support, this is not viable.

**Comment by krishankumar95** [comment]
@blogdoft We do plan to support Admin client which is generally for [entity management operations](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-dotnet).  

For rest of mentioned items, one would use following APIs in a language with supported SDK: 
For checking sent messages without mutating -> PeekMessage API
For ack/nack -> Receive and Complete/DeadLetter

**Comment by Frulfump** [comment]
> [@blogdoft](https://github.com/blogdoft) We do plan to support Admin client which is generally for [entity management operations](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-dotnet).
> 
> For rest of mentioned items, one would use following APIs in a language with supported SDK: For checking sent messages without mutating -> PeekMessage API For ack/nack -> Receive and Complete/DeadLetter

That's great, can you share any type of time line for that? If it's far away in to the future some community effort to bridge the gap would make sense.

**Comment by krishankumar95** [comment]
> > [@blogdoft](https://github.com/blogdoft) We do plan to support Admin client which is generally for [entity management operations](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-dotnet).
> > For rest of mentioned items, one would use following APIs in a language with supported SDK: For checking sent messages without mutating -> PeekMessage API For ack/nack -> Receive and Complete/DeadLetter
> 
> That's great, can you share any type of time line for that? If it's far away in to the future some community effort to bridge the gap would make sense.

Cannot comment on timeline but it should be in near future. So any stop gap solution won't make much sense.

**Comment by zenatureza** [comment]
+1

**Comment by feanz** [comment]
+1

**Comment by csijake** [comment]
Please make sure that when this is added, that retrieving the list of queues/topics is included, as well as retrieving any configuration properties from the queue/topic. (Modifying them is not required, as that should be left to the `Config.json` file.)

Users are unable to connect Service Bus Explorer to the emulator because it attempts to enumerate queues/topics and cannot.

https://github.com/paolosalvatori/ServiceBusExplorer/issues/814

**Comment by mortenn** [comment]
modifying is kind of important, because MassTransit works that way

**Comment by Leitee** [comment]
+1

**Comment by denisulmer** [comment]
This would be much appreciated by a lot of people that use MassTransit e.g.

**Comment by query-wow** [comment]
+1

**Comment by valentingamper** [comment]
+1

**Comment by ChBrockmann** [comment]
@krishankumar95 do you have any news regarding the timelime? I don't want an exact date but will it be weeks or months? 😅

**Comment by kbdavis07** [comment]
+1

**Comment by EwartWigmans-NewOrange** [comment]
+1 still waiting for an update on this

**Comment by ScottKane** [comment]
+1

Why are we still waiting for this after a year? @krishankumar95 please provide an update or tag an appropriate maintainer.

**Comment by bosquig** [comment]
+1

**Comment by Paradiesvogel7** [comment]
+1

**Comment by Saglodha** [comment]
Hi everyone,
Thank you for the continued feedback. I’m pleased to share that the latest Service Bus Emulator release now includes native support for the Service Bus Administration Client in .NET. This enables local management of entities, such as creating, updating, and deleting entities. 

For more details, please refer to the [announcement](https://techcommunity.microsoft.com/blog/messagingonazureblog/introducing-administration-client-support-for-the-azure-service-bus-emulator/4486433) and code [samples](https://github.com/Azure/azure-service-bus-emulator-installer?tab=readme-ov-file#code-samples).

We welcome your continued feedback and look forward to hearing about your experience with this update.

**Comment by SeanFeldman** [comment]
@Saglodha, I was looking to add support for the Emulator in SBE, which is not quite possible at this point, as SBE is using the legacy SDK. But while I was doing that, I noticed that to run `docker compose` with [Docker-Compose-Template/docker-compose-default.yml](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/Docker-Compose-Template/docker-compose-default.yml), it required a `.env`, which wasn't mentioned in the `README.MD`. This could make this easier for those who just want to point and run.

```yml
# 1. Environment file for user defined variables in docker-compose.yml
CONFIG_PATH="../ServiceBus-Emulator/Config/Config.json"

# 2. ACCEPT_EULA: Pass 'Y' to accept license terms for Azure SQL Edge and Azure Service Bus emulator.
ACCEPT_EULA="Y"

# 3. Password must be at least 8 characters and contain uppercase, lowercase, numbers, and special characters
SQL_PASSWORD="SqlPass@1234"
```

Also, the [instructions](https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/README.md#windows) for Windows are outdated and no longer working. Wasn't sure what's the value of those if the emulator could be ran using `docker compose -f .\Docker-Compose-Template\docker-compose-default.yml up`.

Additionally, would be good to explicitly call out that there needs to be 2 connection strings for
1. `ServiceBusAdministrationClient` that includes the port number and
2. `ServiceBusClient`
While it's becoming clear from looking at the samples, it would be good to highlight it as some libraries take a single connection string and that won't work with the emulator.
