### ISSUE TITLE
Support for identity-based connection

### ISSUE THREAD

**Issue by asos-iqan** [Azure/azure-service-bus-emulator-installer#30]
Hi,

The app fails to send or receive messages from servicebus emulator when `ServiceBusClient` was created using identity-based connection.

Steps to reproduce:
```csharp
// running service bus emulator using docker compose before executing this code

using Azure.Identity;
using Azure.Messaging.ServiceBus;

var client = new ServiceBusClient("localhost", new DefaultAzureCredential());
var sender = client.CreateSender("topic");
await sender.SendMessageAsync(new ServiceBusMessage("Hello, World!"));
```

Exception:
```
No connection could be made because the target machine actively refused it. ErrorCode: ConnectionRefused (ServiceCommunicationProblem). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendAsync>b__32_0>d.MoveNext()
--- End of stack trace from previous location ---
```

Does emulator support identity-based connections?
If yes, is there any guidance on what would be the value for service bus fully qualified namespace? (localhost, sbemulatorns, something else...)
If no, are there any plans to support this in future?

**Comment by Saglodha** [comment]
Hi @asos-iqan, Service Bus emulator isn't compatible with Azure Identity based connection. So far, we only support connection string usage with Service Bus emulator. 

Would you mind elaborating more on the use case- Is the intent here to keep same code for local testing and prod testing? Or do you have a use case of using Azure Identity to do local testing?

**Comment by asos-iqan** [comment]
Hi @Saglodha - thanks for the response.
Yes, that is correct. We would like to test function as-is and not have specific changes in production code just to make it work with emulator.

**Comment by Saglodha** [comment]
Thanks for clarifying @asos-iqan. We'll look deeper into this request and share update on this issue in future.

**Comment by mohjohfox** [comment]
Hey, I just want to drop the info, that we also run into the same problem as @asos-iqan. In our code, we are trying to use the same clients as we use in production, where we use azure identity. Without this support, we are forced to build a second client for each queue or topic with a connection string or wait until the emulator supports azure identity. Am I right about this?
I hope you consider supporting this in the future. Looking forward to it as the emulator itself improves local development significantly 👍

**Comment by biggles007** [comment]
If it may take some time to enable Entra support, surely an option would be to disable the authentication check in the ServiceBus via some for of environment variable?

When reading about the limitations this was one of the first issues that came to mind, re: key/connection string based access only. Microsoft themselves push that key based access should be disabled on their services, something that I have been working with clients on rolling out. If they can't use their existing (more secure) code base, then the emulator is pointless for them.
