### ISSUE TITLE
[MassTransit] .NET - No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by decapent** [Azure/azure-service-bus-emulator-installer#32]
When sending a message on the service bus via my .NET Application I receive the following error:

```
System.AggregateException: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (No connection could be made because the target machine actively refused it. (localhost:443)) (No connection could be made because the target machine actively refused it. (localhost:443)) (No connection could be made because the target machine actively refused it. (localhost:443)) (No connection could be made because the target machine actively refused it. (localhost:443))
 ---> Azure.RequestFailedException: No connection could be made because the target machine actively refused it. (localhost:443)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:443)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

I am using the docker compose approach and followed the instructions provided. My application uses MassTransit (might be the culprit ?).

I tried all variations of the Connection string (either by specifiying localhost, localhost:5672, host.docker.internal, the service name itself, 127.0.0.1).

![Image](https://github.com/user-attachments/assets/4bda4d7f-830e-4599-b1ef-f49b5b6887ed)

I updated `Azure.Messaging.ServiceBus` to  `7.18.2` as suggested here because I was experiencing a similar error message : [Can't connect to Emulator](https://github.com/Azure/azure-service-bus-emulator-installer/issues/25#issuecomment-2489176254) 

I can confirm that the container starts properly using the default configuration

```
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Creating user defined entities for SB Emulator
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Creating queue: queue.1 
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Creating topic: topic.1 
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Creating subscription subscription.1 for topic: topic.1 
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Processing filters for subscription subscription.1 for topic: topic.1 
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Processing filter app-prop-filter-1
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Creating subscription subscription.2 for topic: topic.1 
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Processing filters for subscription subscription.2 for topic: topic.1 
2024-11-22 11:39:03 info: a.F.aFu[0]
2024-11-22 11:39:03       Processing filter user-prop-filter-1
2024-11-22 11:39:04 info: a.F.aFu[0]
2024-11-22 11:39:04       Creating subscription subscription.3 for topic: topic.1 
2024-11-22 11:39:04 info: a.F.aFu[0]
2024-11-22 11:39:04       Processing filters for subscription subscription.3 for topic: topic.1 
2024-11-22 11:39:04 info: a.F.aFu[0]
2024-11-22 11:39:04       Triggering Entity Sync
2024-11-22 11:39:04 info: a.F.aFu[0]
2024-11-22 11:39:04       Entity Sync complete; Operation Result:True
2024-11-22 11:39:04 info: a.F.aFu[0]
2024-11-22 11:39:04       User defined entities created for SB Emulator
2024-11-22 11:39:04 info: a.F.aFO[0]
2024-11-22 11:39:04       Emulator Service is Successfully Up!
```

I am out of ideas of what to look into. Any help would be tremendously welcomed :)

**Comment by raix** [comment]
Getting same error using Masstransit and Aspire:
```C#
var serviceBus = builder
    .AddContainer("service-bus", "mcr.microsoft.com/azure-messaging/servicebus-emulator")
    .WithEnvironment("ACCEPT_EULA", "Y")
    .WithEnvironment("SQL_SERVER", "host.docker.internal:9002")
    .WithEnvironment("MSSQL_SA_PASSWORD", sqlPassword)
    .WithHttpEndpoint(5672, 5672)
    .WaitFor(sqlServer);

const string serviceBusConnectionString = "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;";
```

**Comment by danielproctor31** [comment]
@decapent I'm not familiar with MassTransit but based on your log it looks like it's trying to use port 443. I would try opening up that port in the container or looking at changing any config in the application to one of the other open ports.

**Comment by krishankumar95** [comment]
I have created an upstream [issue](https://github.com/MassTransit/MassTransit/issues/5689) at Mass-Transit. SB relies on a connection string parameter `UseDevelopmentEmulator=true;` to signal SDK for Non-TLS localhost communication with Emulator at port 5672. This has to be incorporated within Mass-Transit for it to function with SB Emulator.

**Comment by ericdev1995** [comment]
I got the same error when try using ServiceBusAdministrationClient with connection has parameter `UseDevelopmentEmulator=true; `

**Comment by MattHartz** [comment]
I don't think MassTransit is gonna work regardless until Service Bus Emulator supports management client operations.

Any ideas when that known limitation will be addressed?
