### ISSUE TITLE
Schema Creation Fails When Using mssql/server:2022-Latest

### ISSUE THREAD

**Issue by rsteppac** [Azure/azure-service-bus-emulator-installer#52]
**Describe the bug**
As `azure-sql-edge:latest` apparently has compatibility issues with Linux Kernels >= 6.7 I tried to use `mssql/server:2022-latest` as the storage back-end instead. But schema creation fails with MSSQLServer as the storage backend with an exception:

> Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'id'

while attempting to create the following stored proc:

```sql
create procedure [dbo].[GetEndpointDescriptionById]
    @includeChildren bit,
    @id bigint
as
begin
    set nocount on
    set transaction isolation level read committed
    set xact_abort on

    declare @result int

    if (@includeChildren = 0)
    begin
        set @result = 0
        select @result as 'result'

        select top 1 [ServiceNamespace], [Address], [ResourceType], [State], [InstanceHandle], [GatewaySettings], [Version], [Id], [ParentId], [IsAnonymousAccessible], [ResourceDescription], [Expiration], [Created], [LastModified], [CreationVersion]
        from ResourceManifests
        where [ParentId] is null and [Id] = @id

        select [ResourceManifestId], [EndPartitionRange], [FragmentName], [ContainerId], [PartitionId], [FragmentIndex]
        from [EntityPartitionRangeMappingTable] 
        where [ResourceManifestId] = @id

        select [ResourceManifestId], [EndPartitionRange], [FragmentName], [ContainerId], [ContainerPartitionId]
        from [SubscriptionPartitioningRangeMappingTable]
        where [ResourceManifestId] = @id
    end
    else
    begin
        set @result = 0
        select @result as 'result'

        if (@@rowcount > 0)
        begin
            select [ServiceNamespace], [Address], [ResourceType], [State], [InstanceHandle], [GatewaySettings], [Version], [Id], [ParentId], [IsAnonymousAccessible], [ResourceDescription], [Expiration], [Created], [LastModified], [CreationVersion]
            from ResourceManifests
            where [State] in ('Active', 'Restoring') and [Expiration] >= getutcdate() and [id] = @id and [ParentId] is null
            order by [Address]
            
            select [ServiceNamespace], [Address], [ResourceType], [State], [InstanceHandle], [GatewaySettings], [Version], [Id], [ParentId], [IsAnonymousAccessible], [ResourceDescription], [Expiration], [Created], [LastModified], [CreationVersion]
            from ResourceManifests ed
            where [ed].[ParentId] in (
                select [Id]
                from ResourceManifests
                where [State] in ('Active', 'Restoring') and [Expiration] >= getutcdate() and [id] = @id and [ParentId] is null
            )
        end
    end
end
```

**To Reproduce**
Run `docker compose up` with this compose file:

```yaml
services:
  mssqlHost:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - TZ=Europe/Zurich
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=xxxxx
      - MSSQL_COLLATION=Latin1_General_100_CS_AS_SC_UTF8
      - MSSQL_DB_NAME=some_db
      - MSSQL_DB_USER=sa
    ports:
      - "${MSSQL_SERVER_PORT:-1433}:1433"
    networks:
      - test_net
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -U "$$MSSQL_DB_USER" -P "$$MSSQL_SA_PASSWORD" -Q 'select 1' -b -o /dev/null
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s

  serviceBusEmulator:
    depends_on:
      mssqlHost:
        condition: service_healthy
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: servicebus-emulator
    volumes:
      - "./servicebus-emulator/config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "${ESB_SERVER_PORT:-5672}:5672"
    environment:
      - TZ=Europe/Zurich
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=xxxx
      - SQL_SERVER=mssqlHost
    networks:
      - test_net
```

**Expected behavior**
Schema should be created without errors.

**Logs**
```text
cdr-api-servicebus-emulator  | [11:21:59 WRN] <Trc Id="30510" Ch="Debug" Lvl="Warning" Kw="1000000000000100" UTC="2024-12-10T10:21:59.161Z" Msg="Encountered a SQL Error Code that we do not retry for: error number = 207, error state = 1, error class = 16, error message = Invalid column name &amp;apos;id&amp;apos;., procedure = GetEndpointDescriptionById, line number = 39&#xA;error number = 207, error state = 1, error class = 16, error message = Invalid column name &amp;apos;id&amp;apos;., procedure = GetEndpointDescriptionById, line number = 47&#xA;ExceptionId: 1138f1ac-7e38-4f9e-a693-da4099c027d3-Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name &amp;apos;id&amp;apos;.&#xA;Invalid column name &amp;apos;id&amp;apos;.&#xA;   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)&#xA;   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)&#xA;   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)&#xA;   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp;amp; dataReady)&#xA;   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)&#xA;   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean&amp;amp; usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)&#xA;   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()&#xA;   at a.F.aFN.A.A(SqlCommand)&#xA;   at a.F.aFN.A[T](Func`2)&#xA;ClientConnectionId:1a477b4d-771f-4d09-bbd9-88419759e734&#xA;Error Number:207,State:1,Class:16&#xA;" />
cdr-api-servicebus-emulator  | info: SQL-Setup[0]
cdr-api-servicebus-emulator  |       Error: Sql operation failed... Command: ''
cdr-api-servicebus-emulator  |       create procedure [dbo].[GetEndpointDescriptionById]
cdr-api-servicebus-emulator  |           @includeChildren bit,
cdr-api-servicebus-emulator  |           @id bigint
cdr-api-servicebus-emulator  |       as
cdr-api-servicebus-emulator  |       begin
cdr-api-servicebus-emulator  |           set nocount on
cdr-api-servicebus-emulator  |           set transaction isolation level read committed
cdr-api-servicebus-emulator  |           set xact_abort on
cdr-api-servicebus-emulator  |       
cdr-api-servicebus-emulator  |           declare @result int
cdr-api-servicebus-emulator  |       
cdr-api-servicebus-emulator  |           if (@includeChildren = 0)
cdr-api-servicebus-emulator  |           begin
cdr-api-servicebus-emulator  |               set @result = 0
cdr-api-servicebus-emulator  |               select @result as 'result'
cdr-api-servicebus-emulator  |       
cdr-api-servicebus-emulator  |               select top 1 [ServiceNamespace], [Address], [ResourceType], [State], [InstanceHandle], [GatewaySettings], [Version], [Id], [ParentId], [IsAnonymousAccessible], [ResourceDescription], [Expiration], [Created], [LastModified], [CreationVersion]
cdr-api-servicebus-emulator  |               from ResourceManifests
cdr-api-servicebus-emulator  |               where [ParentId] is null and [Id] = @id
cdr-api-servicebus-emulator  |       
cdr-api-servicebus-emulator  |               select [ResourceManifestId], [EndPartitionRange], [FragmentName], [ContainerId], [PartitionId], [FragmentIndex]
cdr-api-servicebus-emulator  |               from [EntityPartitionRangeMappingTable] 
cdr-api-servicebus-emulator  |               where [ResourceManifestId] = @id
cdr-api-servicebus-emulator  |       
cdr-api-servicebus-emulator  |               select [ResourceManifestId], [EndPartitionRange], [FragmentName], [ContainerId], [ContainerPartitionId]
cdr-api-servicebus-emulator  |               from [SubscriptionPartitioningRangeMappingTable]
cdr-api-servicebus-emulator  |               where [ResourceManifestId] = @id
cdr-api-servicebus-emulator  |           end
cdr-api-servicebus-emulator  |           else
cdr-api-servicebus-emulator  |           begin
cdr-api-servicebus-emulator  |               set @result = 0
cdr-api-servicebus-emulator  |               select @result as 'result'
cdr-api-servicebus-emulator  |       
cdr-api-servicebus-emulator  |               if (@@rowcount > 0)
cdr-api-servicebus-emulator  |               begin
cdr-api-servicebus-emulator  |                   select [ServiceNamespace], [Address], [ResourceType], [State], [InstanceHandle], [GatewaySettings], [Version], [Id], [ParentId], [IsAnonymousAccessible], [ResourceDescription], [Expiration], [Created], [LastModified], [CreationVersion]
cdr-api-servicebus-emulator  |                   from ResourceManifests
cdr-api-servicebus-emulator  |                   where [State] in ('Active', 'Restoring') and [Expiration] >= getutcdate() and [id] = @id and [ParentId] is null
cdr-api-servicebus-emulator  |                   order by [Address]
cdr-api-servicebus-emulator  |                   
cdr-api-servicebus-emulator  |                   select [ServiceNamespace], [Address], [ResourceType], [State], [InstanceHandle], [GatewaySettings], [Version], [Id], [ParentId], [IsAnonymousAccessible], [ResourceDescription], [Expiration], [Created], [LastModified], [CreationVersion]
cdr-api-servicebus-emulator  |                   from ResourceManifests ed
cdr-api-servicebus-emulator  |                   where [ed].[ParentId] in (
cdr-api-servicebus-emulator  |                       select [Id]
cdr-api-servicebus-emulator  |                       from ResourceManifests
cdr-api-servicebus-emulator  |                       where [State] in ('Active', 'Restoring') and [Expiration] >= getutcdate() and [id] = @id and [ParentId] is null
cdr-api-servicebus-emulator  |                   )
cdr-api-servicebus-emulator  |               end
cdr-api-servicebus-emulator  |           end
cdr-api-servicebus-emulator  |       end
cdr-api-servicebus-emulator  |       ''. Exception: ''Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'id'.
cdr-api-servicebus-emulator  |       Invalid column name 'id'.
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
cdr-api-servicebus-emulator  |          at a.F.aFN.A.A(SqlCommand)
cdr-api-servicebus-emulator  |          at a.F.aFN.A[T](Func`2)
cdr-api-servicebus-emulator  |       ClientConnectionId:1a477b4d-771f-4d09-bbd9-88419759e734
cdr-api-servicebus-emulator  |       Error Number:207,State:1,Class:16''
cdr-api-servicebus-emulator  | fail: a.F.aFO[0]
cdr-api-servicebus-emulator  |       Error occured while running emulator launcher: Invalid column name 'id'.
cdr-api-servicebus-emulator  |       Invalid column name 'id'.
cdr-api-servicebus-emulator  |       Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'id'.
cdr-api-servicebus-emulator  |       Invalid column name 'id'.
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
cdr-api-servicebus-emulator  |          at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
cdr-api-servicebus-emulator  |          at a.F.aFN.A.A(SqlCommand)
cdr-api-servicebus-emulator  |          at a.F.aFN.A[T](Func`2)
cdr-api-servicebus-emulator  |          at a.F.aFN.E()
cdr-api-servicebus-emulator  |          at a.F.aFL.A(String[], String)
cdr-api-servicebus-emulator  |          at a.F.aFL.a(DatabaseType, DatabaseAction)
cdr-api-servicebus-emulator  |          at a.F.aFL.A(DatabaseType, DatabaseAction)
cdr-api-servicebus-emulator  |          at a.F.aFU.A()
cdr-api-servicebus-emulator  |          at a.F.aFO.StartAsync(CancellationToken)
cdr-api-servicebus-emulator  |       ClientConnectionId:1a477b4d-771f-4d09-bbd9-88419759e734
cdr-api-servicebus-emulator  |       Error Number:207,State:1,Class:16
```

**Desktop:**
 - OS: Ubuntu 24.04, Kernel 6.8.0-49-generic

**Image Platform-Architecture Used:**
Linux-amd64

**Docker Version:**
```text
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:28:55 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:28:55 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Arguments && Environment variables to start Emulator:**
  - TZ=Europe/Zurich
  - ACCEPT_EULA=Y
  - MSSQL_SA_PASSWORD=xxxx
  - SQL_SERVER=mssqlHost

**Emulator Launch Configuration:**
- Include the `Config.json` file used for launching the emulator. Below is a sample of the current checked-in `Config.json`:

```json
{
  "UserConfig": {
    "Namespaces": [
      {
        "Name": "sbemulatorns",
        "Queues": [],
        "Topics": [
          {
            "Name": "documentdispatchedcdrtopic",
            "Properties": {
              "DefaultMessageTimeToLive": "PT1H",
              "DuplicateDetectionHistoryTimeWindow": "PT20S",
              "RequiresDuplicateDetection": false
            },
            "Subscriptions": [
              {
                "Name": "subscription.1",
                "Properties": {
                  "DeadLetteringOnMessageExpiration": false,
                  "DefaultMessageTimeToLive": "PT1H",
                  "LockDuration": "PT1M",
                  "MaxDeliveryCount": 10,
                  "ForwardDeadLetteredMessagesTo": "",
                  "ForwardTo": "",
                  "RequiresSession": false
                },
                "Rules": []
              }
            ]
          }
        ]
      }
    ],
    "Logging": {
      "Type": "Console"
    }
  }
}
```

**Emulator Launch Method:**
Direct Docker compose

**Comment by krishankumar95** [comment]
@rsteppac ; Dropping the following section and letting SQL Server use its default collation should resolve the issue. 

```
    - MSSQL_COLLATION=Latin1_General_100_CS_AS_SC_UTF8
```

If you are sharing the SQL container with some other application and need a specific collation; you can spin up emulator specific SQL container on a different port and pass that along to the Emulator.
```
```

**Comment by rsteppac** [comment]
@krishankumar95 , using an instance with default collation worked.
